#!/bin/bash -xe

. ./hooks/env

TAG_PREFIX=${DOCKER_TAG%-*}
IMAGE_PREFIX="${IMAGE_NAME%-*}"
ARCH_LIST="amd64 $(ls -1 Dockerfile.* | sed 's|Dockerfile.||')"
IMAGE_LIST=""
for i in ${ARCH_LIST}; do
  IMAGE_LIST="${IMAGE_LIST}${IMAGE_PREFIX}-${i} "
done

: ${PA_TOKEN:?PA_TOKEN not configured} ${PA_USER:?PA_USER not configured}
${DOCKER_CLI} login -u "${PA_USER}" -p "${PA_TOKEN}" >/dev/null 2>&1

function manifest_annotate {
  ${DOCKER_CLI} manifest annotate $1 ${IMAGE_PREFIX}-arm --os linux --arch "arm" --variant "7"
  ${DOCKER_CLI} manifest annotate $1 ${IMAGE_PREFIX}-arm64 --os linux --arch "arm64" --variant "8"
}

${DOCKER_CLI} manifest create --amend ${IMAGE_PREFIX} ${IMAGE_LIST} || exit 0
manifest_annotate "${IMAGE_PREFIX}"
${DOCKER_CLI} manifest push -p "${IMAGE_PREFIX}"
if [ "${TAG_PREFIX}" != "latest" ]; then
  ${DOCKER_CLI} manifest create --amend "${IMAGE_PREFIX%.*}" ${IMAGE_LIST}
  manifest_annotate "${IMAGE_PREFIX%.*}"
  ${DOCKER_CLI} manifest push -p "${IMAGE_PREFIX%.*}"
  ${DOCKER_CLI} manifest create --amend "${DOCKER_REPO}:latest" ${IMAGE_LIST}
  manifest_annotate "${DOCKER_REPO}:latest"
  ${DOCKER_CLI} manifest push -p "${DOCKER_REPO}:latest"
fi
